### ISSUE TITLE
Updated References to old hostname for DreamObjects

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dreamobjects#12]
I got a message from a user regarding an upcoming change in the DreamHost DreamObjects: 

```
Please update the connection settings of whichever apps you use to access DreamObjects as soon as possible. The old hostname will stop working onJanuary 9th, 2017. If you have already updated references to the old hostname within the last 30 days, you can ignore this notification.
```

He wasn't sure if the hostname they were referring to was his own or if it was part of the plugin or not? 

cc @pdewouters - not sure who else would know more about this?

**Comment by pdewouters** [comment]
might be this: https://github.com/humanmade/backupwordpress-pro-dreamobjects/blob/master/inc/DreamObjectsBackUpService.php#L187

**Comment by katmoody** [comment]
@pdewouters - I want to make sure I understand this right ... so the host you highlighted in line 187 above is the hostname for Dreamobjects? If so, then the new hostname for DreamObjects is objects-us-west-1.dream.io according to their API documentation (if I understand their example: https://help.dreamhost.com/hc/en-us/articles/214948128-Getting-Started-using-DreamObjects-object-store-API

So I just need to update the URL at that line? Do we have a test to confirm it connects successfully?
